CREATE TABLE IF NOT EXISTS task (	
id BIGSERIAL PRIMARY KEY,
title VARCHAR(120) NOT NULL,
description TEXT NOT NULL,
status VARCHAR(10) NOT NULL, 
created_at TIMESTAMP WITHOUT TIME ZONE,
updated_at TIMESTAMP WITHOUT TIME ZONE,
deleted BOOLEAN DEFAULT FALSE NOT NULL
);
